# Generated by Django 3.1 on 2020-08-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotosVideos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='img_src',
            field=models.ImageField(upload_to='static/pics/'),
        ),
    ]
