# Generated by Django 3.1 on 2020-08-13 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotosVideos', '0002_auto_20200812_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=300)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='post_files')),
            ],
        ),
    ]
