# Generated by Django 3.1 on 2020-08-13 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PhotosVideos', '0004_auto_20200813_0123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='video_file',
            new_name='video_url',
        ),
    ]
